### PR TITLE
added includes for forward declarations to match gcc requirements

### PR DESCRIPTION
**Pull request by hemker**
Current version was not compiling with gcc5 and ubuntu 16.04

### CODE REVIEW

**Comment by jmachowinski** [comment]
@doudou This might also be a bug in orogen, that the correct headers are not include. Could you have a look at it ?

**Comment by doudou** [comment]
All .hpp and .cpp files should be self-contained header-wise (i.e. never assume that orogen will include them for you behind the scenes).

**Comment by hemker** [comment]
but why did it work with gcc4 and ubuntu 14.04??

**Comment by jmachowinski** [comment]
There is a behaviour change of orogen between Ubuntu 14.04 and Ubuntu 16.04.
/.orogen/typekit/types/kdl/typekit/OpaqueTypes.hpp
under 14.04 looks like this :
`#include <kdl/KDL/wrappers/KDLTypes.hpp>`
`#include <kdl/chain.hpp>`
`#include <kdl/frames.hpp>`
`#include <kdl/jacobian.hpp>`
`#include <kdl/jntarray.hpp>`
`#include <kdl/joint.hpp>`
`#include <kdl/rigidbodyinertia.hpp>`
`#include <kdl/rotationalinertia.hpp>`
`#include <kdl/segment.hpp>`
`#include <vector>`

While 16.04 looks like this:
`#include <kdl/KDL/wrappers/KDLTypes.hpp>`
`#include <vector>`

As the orogen versions are identical, I assume this is caused by CastXML. 
I am just wondering, which behaviour is the desired one...

**Comment by jmachowinski** [comment]
As there is no harm in the pull request, and it fixes the issue in 16.04 I'll merge...

**Pull request merged**
